//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Комнаты.
    /// </summary>
    // *** Start programmer edit section *** (Комнаты CustomAttributes)

    // *** End programmer edit section *** (Комнаты CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Комнаты : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерКомнаты;
        
        private double fПлощадь;
        
        private IIS.Test1.Здание fЗдание;
        
        // *** Start programmer edit section *** (Комнаты CustomMembers)

        // *** End programmer edit section *** (Комнаты CustomMembers)

        
        /// <summary>
        /// НомерКомнаты.
        /// </summary>
        // *** Start programmer edit section *** (Комнаты.НомерКомнаты CustomAttributes)

        // *** End programmer edit section *** (Комнаты.НомерКомнаты CustomAttributes)
        public virtual int НомерКомнаты
        {
            get
            {
                // *** Start programmer edit section *** (Комнаты.НомерКомнаты Get start)

                // *** End programmer edit section *** (Комнаты.НомерКомнаты Get start)
                int result = this.fНомерКомнаты;
                // *** Start programmer edit section *** (Комнаты.НомерКомнаты Get end)

                // *** End programmer edit section *** (Комнаты.НомерКомнаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Комнаты.НомерКомнаты Set start)

                // *** End programmer edit section *** (Комнаты.НомерКомнаты Set start)
                this.fНомерКомнаты = value;
                // *** Start programmer edit section *** (Комнаты.НомерКомнаты Set end)

                // *** End programmer edit section *** (Комнаты.НомерКомнаты Set end)
            }
        }
        
        /// <summary>
        /// Площадь.
        /// </summary>
        // *** Start programmer edit section *** (Комнаты.Площадь CustomAttributes)

        // *** End programmer edit section *** (Комнаты.Площадь CustomAttributes)
        public virtual double Площадь
        {
            get
            {
                // *** Start programmer edit section *** (Комнаты.Площадь Get start)

                // *** End programmer edit section *** (Комнаты.Площадь Get start)
                double result = this.fПлощадь;
                // *** Start programmer edit section *** (Комнаты.Площадь Get end)

                // *** End programmer edit section *** (Комнаты.Площадь Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Комнаты.Площадь Set start)

                // *** End programmer edit section *** (Комнаты.Площадь Set start)
                this.fПлощадь = value;
                // *** Start programmer edit section *** (Комнаты.Площадь Set end)

                // *** End programmer edit section *** (Комнаты.Площадь Set end)
            }
        }
        
        /// <summary>
        /// Комнаты.
        /// </summary>
        // *** Start programmer edit section *** (Комнаты.Здание CustomAttributes)

        // *** End programmer edit section *** (Комнаты.Здание CustomAttributes)
        [PropertyStorage(new string[] {
                "Здание"})]
        [NotNull()]
        public virtual IIS.Test1.Здание Здание
        {
            get
            {
                // *** Start programmer edit section *** (Комнаты.Здание Get start)

                // *** End programmer edit section *** (Комнаты.Здание Get start)
                IIS.Test1.Здание result = this.fЗдание;
                // *** Start programmer edit section *** (Комнаты.Здание Get end)

                // *** End programmer edit section *** (Комнаты.Здание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Комнаты.Здание Set start)

                // *** End programmer edit section *** (Комнаты.Здание Set start)
                this.fЗдание = value;
                // *** Start programmer edit section *** (Комнаты.Здание Set end)

                // *** End programmer edit section *** (Комнаты.Здание Set end)
            }
        }
    }
}
